### PR TITLE
Make ghc-8.6.4 the recommended GHC

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
The thing is, we don't have FreeBSD tarballs yet, so what to do?

**Comment by hasufell** [comment]
https://gitlab.haskell.org/ghc/ghc/issues/16134

**Comment by hasufell** [comment]
@gwils

**Comment by gwils** [comment]
I don't have a good answer. It might be worth breaking FreeBSD in the meantime? Ideally we'd get the FreeBSD CI up and running. I don't have the skills for that or time to acquire them right now.

**Pull request closed without merging**
